<?php

namespace AppBundle\Entity\Repository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllIndexedById()
    {
        return $this->getEntityManager()
            ->createQuery("SELECT c
                           FROM AppBundle:Company c
                           INDEX BY c.id
                           ORDER BY c.name")
            ->getResult();

    }
}
