<?php

namespace AppBundle\Entity\Repository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllIndexedById($user = null)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT c
                           FROM AppBundle:Company c
                           INDEX BY c.id
                           WHERE :user IS NULL OR c.user = :user 
                           ORDER BY c.name")
            ->setParameter('user', $user)
            ->getResult();
    }
}
