<?php

namespace AppBundle\Entity\Repository;

/**
 * PriceListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceListRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithRelations($id)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT pl, plp, p, c
                           FROM AppBundle:PriceList pl
                           INDEX BY pl.id
                           JOIN pl.priceListProducts plp
                           JOIN plp.product p
                           LEFT JOIN pl.company c
                           WHERE pl.id = :id")
            ->setParameter('id', $id)
            ->getOneOrNullResult();
    }


    public function findQueryByUser($user, $startDate, $endDate)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT pl, plp, p, c
                           FROM AppBundle:PriceList pl
                           INDEX BY pl.id
                           JOIN pl.priceListProducts plp
                           JOIN plp.product p
                           LEFT JOIN pl.company c
                           WHERE (pl.user = :user OR :user IS NULL)
                               AND (pl.performDate >= :startDate OR :startDate IS NULL)
                               AND (pl.performDate <= :endDate OR :endDate IS NULL)
                           ORDER BY pl.id DESC")
            ->setParameter('user', $user)
            ->setParameter('startDate', $startDate)
            ->setParameter('endDate', $endDate);
    }

    public function findPriceListsTotal($priceListIds)
    {
        if (count($priceListIds) == 0){
            return [];
        }

        return $this->getEntityManager()
            ->createQuery("SELECT pl.id, SUM(p.price * plp.quantity) as total
                           FROM AppBundle:PriceList pl
                           INDEX BY pl.id
                           JOIN pl.priceListProducts plp
                           JOIN plp.product p
                           WHERE pl.id IN (:ids)
                           GROUP BY pl.id")
            ->setParameter('ids', $priceListIds)
            ->getResult();
    }

    public function findStatistic($userId, $companyId, $startDate, $endDate)
    {
        $startDate = $startDate ? $startDate : null;
        $endDate = $endDate ? $endDate : null;

        return $this->getEntityManager()
            ->createQuery("SELECT  p.id, p.name, p.price, SUM(plp.quantity) as quantity
                           FROM AppBundle:priceList pl
                           JOIN pl.priceListProducts plp
                           JOIN plp.product p
                           WHERE ((:company IS NOT NULL AND pl.company = :company) OR (:user IS NOT NULL AND pl.user = :user))
                           AND plp.quantity != 0
                           AND (pl.performDate >= :startDate OR :startDate IS NULL)
                           AND (pl.performDate <= :endDate OR :endDate IS NULL)
                           GROUP BY p.id
                           ORDER BY p.id")
            ->setParameter('user', $userId)
            ->setParameter('company', $companyId)
            ->setParameter('startDate', $startDate)
            ->setParameter('endDate', $endDate)
            ->getResult();
    }
}
