<?php

namespace AppBundle\Entity\Repository;

/**
 * PriceListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceListRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUser($user)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT pl, plp, p, c
                           FROM AppBundle:PriceList pl
                           INDEX BY pl.id
                           JOIN pl.priceListProducts plp
                           JOIN plp.product p
                           LEFT JOIN pl.company c
                           WHERE pl.user = :user OR :user IS NULL
                           ORDER BY pl.performDate DESC")
            ->setParameter('user', $user)
            ->getResult();
    }

    public function findPriceListsTotal($priceListIds)
    {
        if (count($priceListIds) == 0){
            return [];
        }

        return $this->getEntityManager()
            ->createQuery("SELECT pl.id, SUM(p.price * plp.quantity) as total
                           FROM AppBundle:PriceList pl
                           INDEX BY pl.id
                           JOIN pl.priceListProducts plp
                           JOIN plp.product p
                           WHERE pl.id IN (:ids)
                           GROUP BY pl.id")
            ->setParameter('ids', $priceListIds)
            ->getResult();
    }

    public function findStatistic($companyId, $startDate, $endDate)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT p.name, SUM(plp.quantity)
                           FROM AppBundle:PriceList pl
                           JOIN pl.priceListProducts plp
                           JOIN plp.product p
                           WHERE pl.company = :company
                           GROUP BY p.name")
            ->setParameter('company', $companyId)
            ->getResult();
    }
}
