<?php

namespace AppBundle\Entity\Repository;
use AppBundle\Entity\Product;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllIndexedById($type = Product::ECONOMIC)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT p
                           FROM AppBundle:Product p
                           INDEX BY p.id
                           WHERE p.enabled = true and p.type = :type
                           ORDER BY p.name")
            ->setParameter('type', $type)
            ->getResult();
    }
}
