<?php

namespace AppBundle\Entity\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllIndexedById()
    {
        return $this->getEntityManager()
            ->createQuery("SELECT p
                           FROM AppBundle:Product p
                           INDEX BY p.id
                           WHERE p.enabled = true
                           ORDER BY p.name")
            ->getResult();
    }
}
